# Generated by Django 3.2.7 on 2021-10-07 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='birthday',
            new_name='birthdate',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='subject',
            new_name='department',
        ),
    ]
