# Generated by Django 3.2.7 on 2021-10-13 08:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_auto_20211007_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='birthdate',
            field=models.DateField(default=datetime.datetime(2021, 10, 13, 8, 30, 16, 7556, tzinfo=utc), null=True),
        ),
    ]
