# Generated by Django 3.2.7 on 2021-11-11 12:26

import datetime
from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import phonenumber_field.modelfields
import student.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("courses", "__first__"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExtendedUser",
            fields=[],
            options={
                "ordering": ("first_name",),
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("auth.user",),
            managers=[
                ("people", django.db.models.manager.Manager()),
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("TC", "Teacher"),
                            ("ST", "Student"),
                            ("MT", "Mentor"),
                        ],
                        default="ST",
                        max_length=2,
                    ),
                ),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        help_text="Contact phone number",
                        max_length=128,
                        region="UA",
                    ),
                ),
                (
                    "birthdate",
                    models.DateField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                ("photo", models.ImageField(upload_to="media/photos/")),
                (
                    "course",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="courses.course",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        max_length=60,
                        validators=[django.core.validators.MinLengthValidator(2)],
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        max_length=80,
                        validators=[django.core.validators.MinLengthValidator(2)],
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=120,
                        null=True,
                        unique=True,
                        validators=[
                            student.validators.no_elon_validator,
                            student.validators.domain_validator,
                        ],
                    ),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, null=True, region=None, unique=True
                    ),
                ),
                (
                    "birthdate",
                    models.DateField(
                        default=datetime.date.today,
                        null=True,
                        validators=[student.validators.age_validator],
                    ),
                ),
                ("enroll_date", models.DateField(default=datetime.date.today)),
                (
                    "graduate_date",
                    models.DateField(default=datetime.date.today, null=True),
                ),
                (
                    "photo",
                    models.ImageField(blank=True, default="default.png", upload_to=""),
                ),
                (
                    "cv",
                    models.FileField(
                        blank=True,
                        default="default.txt",
                        upload_to="",
                        validators=[student.validators.validate_file_extension],
                    ),
                ),
                ("number_of_referals", models.IntegerField(default=0, null=True)),
                (
                    "course",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="courses.course",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
