# Generated by Django 3.2.7 on 2021-10-10 07:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20211010_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(max_length=14, null=True, validators=[django.core.validators.RegexValidator('\\d{10-14}')]),
        ),
    ]
