# Generated by Django 3.2.7 on 2021-10-12 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20211003_1102'),
        ('student', '0005_alter_student_phone_number'),
    ]

    operations = [
    ]
