# Generated by Django 3.2.7 on 2021-10-13 08:49

from django.db import migrations, models
import student.validators


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_alter_student_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=120, null=True, validators=[student.validators.no_elon_validator, student.validators.domain_validator]),
        ),
    ]
