# Generated by Django 3.2.7 on 2021-10-13 09:12

import datetime
from django.db import migrations, models
import student.validators


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_alter_student_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='birthdate',
            field=models.DateField(default=datetime.date.today, null=True, validators=[student.validators.age_validator]),
        ),
    ]
