# Generated by Django 3.2.7 on 2021-10-07 10:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='start_date',
            field=models.DateField(default=datetime.date(2021, 10, 7), null=True),
        ),
    ]
